apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: bookstore-ns
spec:
  replicas: 1
  # The circuit‑breaker state is stored on disk in a pod‑local file
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      volumes:
        - name: cb-state
          emptyDir: {}       # pod‑local ephemeral storage
      containers:
      - name: book-service
        # image: jigyasag/ediss-a2:book-service-v1
        image: jigyasag/ediss-a3-book-service:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # ── 4. Mount the volume where the controller writes state.json ──
        volumeMounts:
          - name: cb-state
            mountPath: /circuit
        env:
        # Location	API documentation	Delay	Purpose
        # http://18.118.230.221	http://18.118.230.221/swagger-ui.html	varies	Gradescope submission
        # http://3.130.6.49	http://3.130.6.49/swagger-ui.html	zero	Testing locally or on AWS (prior to submission)
        # http://localhost:<port>	http://localhost:<port>/swagger-ui.html	as you define	Local tests prior to AWS deployment
        - name: RECOMMENDER_URL
          value: "http://18.118.230.221" # update later
        - name: DB_HOST
          value: "bookstore-db-dev.cluster-cd20i0i40rro.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "edispass"
        - name: DB_NAME
          value: "bookstore"
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
