apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
      - name: crm-service
        image: jigyasag/ediss-a3-crm-service:v3 ###TO DO: Update the image name  
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        # Kafka consumer
        - name: KAFKA_BOOTSTRAP
          value: "3.129.102.184:9092,18.118.230.221:9093,3.130.6.49:9094"
        - name: TOPIC
          # value: "<your_andrew_id>.customer.evt"
          value: "jigyasag.customer.evt"
        # SMTP credentials (from a Secret)
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_USER
          value: "jigyasatata2@gmail.com"
          # valueFrom:
          #   secretKeyRef:
          #     name: smtp-secret
          #     key: user
        - name: SMTP_PASS
          # valueFrom:
          #   secretKeyRef:
          #     name: smtp-secret
          #     key: pass
          value: "cxnk gzyy xqvo rhrd"
        - name: ANDREW_ID
          value: "jigyasag"
        livenessProbe:
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10


# kubectl create secret generic smtp-secret \
  # --from-literal=user='you@gmail.com' \
  # --from-literal=pass='YOUR16CHAR_APP_PASSWORD' \
  # -n bookstore-ns
