apiVersion: v1
kind: Service
metadata:
  name: mobile-bff
  namespace: bookstore-ns
spec:
  selector:
    app: mobile-bff
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer # This creates an AWS ELB