apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bff
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-bff
  template:
    metadata:
      labels:
        app: web-bff
    spec:
      containers:
      - name: web-bff
        image: jigyasag/ediss-a3-mobile-bff:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: URL_BASE_BACKEND_SERVICES_BOOK
          value: "http://ae3b2c10c56b6418681e8d267af2af2e-362494195.us-east-1.elb.amazonaws.com:3000" ##Updated using kubectl get services -n bookstore-ns : Book Service
        - name: URL_BASE_BACKEND_SERVICES_CUSTOMER
          value: "http://ac6f853fb52da47f6b76cb881270f25b-488998332.us-east-1.elb.amazonaws.com:3000"  ##Updated using kubectl get services -n bookstore-ns : Customer Service
        - name: PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10